### ISSUE TITLE
character selection / OnCharacterStart - MissingMethodException

### ISSUE THREAD

**Issue by 0DarkHack0** [DeepWolf413/Cozyheim-Mods#11]
Hi
I have a problem, as soon as I start with the mod "DifficultyScaler_Fixed v0.1.6" on
the latest game version, I get the following error as soon as I see the character and when
I enter the world my character clones itself 4-6 times per second without a break.

`[Info   : Unity Log] 05/29/2024 19:56:16: OnCharacterStart

[Info   : Unity Log] 05/29/2024 19:56:41: show character selection

[Error  : Unity Log] MissingMethodException: Method not found: bool .EnvMan.IsNight()
Stack trace:
(wrapper dynamic-method) Character.DMD<Character::Awake>(Character)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::Awake>(Humanoid)
(wrapper dynamic-method) Player.DMD<Player::Awake>(Player)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
FejdStartup:SetupCharacterPreview(PlayerProfile)
FejdStartup:OnCharacterNew()
UnityEngine.EventSystems.EventSystem:Update()

[Info   :Jotunn.Managers.SkillManager] Registering 1 custom skills
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.SetSkinColor (UnityEngine.Vector3 color) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerCustomizaton.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.SetHairColor (UnityEngine.Vector3 color) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerCustomizaton.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.SetPlayerModel (System.Int32 index) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerCustomizaton.SetPlayerModel (System.Int32 index) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.CachedInvokableCall`1[T].Invoke (System.Object[] args) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.UI.Toggle.Set (System.Boolean value, System.Boolean sendCallback) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.Toggle.set_isOn (System.Boolean value) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.Toggle.InternalToggle () (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.Toggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.SetPlayerModel (System.Int32 index) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerCustomizaton.SetPlayerModel (System.Int32 index) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.CachedInvokableCall`1[T].Invoke (System.Object[] args) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.UI.Toggle.Set (System.Boolean value, System.Boolean sendCallback) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.Toggle.set_isOn (System.Boolean value) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.Toggle.InternalToggle () (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.UI.Toggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <4043a6cf2c744415844c8ec0cca11c21>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.SetSkinColor (UnityEngine.Vector3 color) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerCustomizaton.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.SetSkinColor (UnityEngine.Vector3 color) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerCustomizaton.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Player.SetHairColor (UnityEngine.Vector3 color) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerCustomizaton.Update () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Warning: Unity Log] Error loading player data: C:/Users/PC/AppData/LocalLow/IronGate/Valheim/characters_local/test.fch, error: Value cannot be null.
Parameter name: key`

![valheim_LOgvJShFGN](https://github.com/DeepWolf413/Cozyheim-Mods/assets/171190915/8445ae21-5546-4fb6-bcd7-3cac90a544ee)
![valheim_x9iIPzs3c5](https://github.com/DeepWolf413/Cozyheim-Mods/assets/171190915/e3156621-225a-46cb-8349-a0e1f9377e04)
![valheim_kxOmdymap1](https://github.com/DeepWolf413/Cozyheim-Mods/assets/171190915/373364d6-216b-4bea-880e-d19d803fb5e5)
![valheim_7MidA3osiG](https://github.com/DeepWolf413/Cozyheim-Mods/assets/171190915/267d4aed-d427-4673-818b-0225403e648b)

**Comment by DeepWolf413** [comment]
Oh wow, that looks crazy. I'll fix the mod for Ashlands as soon as possible. My weekend is a bit busy, so It probably won't be until after the weekend.
Apologies for the inconvenience :-)

**Comment by 0DarkHack0** [comment]
No problem, I'm still playing on the older version of the game, but the cloning was really funny XD
But it's nice to hear that an update is coming soon, thank you very much for that : D

**Comment by DeepWolf413** [comment]
Hi! I released a new update for the mod on Thunderstore. I did a quick test and it seems to work fine now :-)

**Comment by 0DarkHack0** [comment]
> Hi! I released a new update for the mod on Thunderstore. I did a quick test and it seems to work fine now :-)

I can confirm it, everything works perfectly, thank you very much for fixing it and for your great mods : D

Do you know a mod where loot bags drop from enemies instead of individual items or where if too many drop then they drop in a stack? I'm still looking for something like that ^^ maybe you can finish such a mod <3

**Comment by DeepWolf413** [comment]
Perfect :-D I think I saw a mod like that a while ago, but I can't remember the name of it. I'll add it to the ideas list and have a go at it eventually :-)

**Comment by 0DarkHack0** [comment]
> Perfect :-D I think I saw a mod like that a while ago, but I can't remember the name of it. I'll add it to the ideas list and have a go at it eventually :-)

That's good to hear,
prevent a crash + better performance by drops if too many individual items drop and are stacked too late.
Is also good if you have mods that increase the level of the enemies and can have 6-12 stars.

Maybe you can let the monster drop a little more slowly once it has a certain number of stars as protection against crashes, e.g. a certain number of items so that the game can stack it first and then continue to drop items, something like that

or have it requested directly as soon as 2 or more of the same item type drop and they are stackable, then they drop stacked.

or as a loot box, which I'm sure not many would like, maybe as an extra option.

I'm urgently looking for a mod like that, I'd even give you a 50€ tip for it *_* so that everyone can benefit from the mod
