### ISSUE TITLE
errror on logout

### ISSUE THREAD

**Issue by PaloAlo** [DeepWolf413/Cozyheim-Mods#12]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Cozyheim.LevelingSystem.XPManager.SetPlayerLevel (System.Int32 level) (at <213946ecdcaa4e0ea59f4fe6db2055be>:0)
Cozyheim.LevelingSystem.UIManager.DestroySelf () (at <213946ecdcaa4e0ea59f4fe6db2055be>:0)
Cozyheim.LevelingSystem.PatchXP_Monster+PatchClass.Game_Logout_Prefix () (at <213946ecdcaa4e0ea59f4fe6db2055be>:0)
(wrapper dynamic-method) Game.DMD<Game::Logout>(Game,bool,bool)
(wrapper dynamic-method) Menu.DMD<Menu::Logout>(Menu)
Menu.OnLogoutYes () (at <f2bd4707b2634fe984bbd9f1a6151f91>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.UI.Button.Press () (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <c784ba61915748ee8776f4834d413c9a>:0)
UnityEngine.EventSystems.EventSystem:Update()

im getting this on logout, ashlands build 218.15
single player mode
i was using Infinity Hammer and it errored forcing a game freeze, i tried to logout with the esc menu and this error came out. i had to force close the game.

**Comment by PaloAlo** [comment]
hi again, so im still having an issue on logout and death. player death causes an issue i have reported on OdinPlus here https://discord.com/channels/826573164371902465/826588965116182538/1263959161457217727

i have very few mods that affect skills so i have a feeling that out of the maybe four mods that might be suspect that leveling system is most likely to be the one causing this since it deals extensively with skills. can you take a look at the link above, read my comments, check the logfile i attached please? 

this issue has been going on for a while now, and is quite annoying. players will log back in in a different location, and their vanilla skills will not be saved at logout/death. 

consequently i think its causing a subsequent issue with DiscConnector since it cant report logouts/deaths correctly.

**Comment by DeepWolf413** [comment]
Awesome, glad to hear you got it sorted out :-) 👍
