### ISSUE TITLE
Build menu issue

### ISSUE THREAD

**Issue by VamPerL** [DeepWolf413/Cozyheim-Mods#8]
Hey there, 
I have an error popping up when opening the build menu:
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Cozyheim.LevelingSystem.PatchXP_Monster+PatchClass.Hud_SetupPieceInfo_Prefix (UnityEngine.UI.Text& ___m_buildSelection, UnityEngine.UI.Text& ___m_pieceDescription, UnityEngine.GameObject[]& ___m_requirementItems) (at <165d13eb6c074f66bc73e85416bd6715>:0)
(wrapper dynamic-method) Hud.DMD<Hud::SetupPieceInfo>(Hud,Piece)
(wrapper dynamic-method) Hud.DMD<Hud::UpdateBuild>(Hud,Player,bool)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)`

And attached you'll find how it looks like.
Thank you so much in advance and let me know, if I can assist somehow. 

PS: I didn't have the wood roof selected in the screenshot, it just stays at that no matter which build piece I select. 
![2023-10-23 18_19_28-Window](https://github.com/DeepWolf413/Cozyheim-Mods/assets/80795460/fb875d1a-ac40-469d-9815-aaa883417a7b)

**Comment by DeepWolf413** [comment]
Hi, I'll release an update ASAP today :-)

**Comment by DeepWolf413** [comment]
Fixed and uploaded :-)
